spring:
  datasource:
    url: jdbc:mysql://localhost:3306/persondb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: Admin.A.1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  redis:
    host: localhost
    port: 6379

jwt:
  secret: my_jwt_secret_key
